# Site settings
title: Mauro Cendon Hidalgo
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mauro Cendon Hidalgo
user_title: Software Engineer
email: mau.cendon@gmail.com
avatar: https://avatars1.githubusercontent.com/u/7624862?s=460&v=4
# twitter_username: lorem_ipsum
github_username:  maucendon
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-137188807-1"

exclude: ['package.json', 'src' , 'node_modules']

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem